package com.example.experimentify;

import android.content.Context;
import android.widget.ArrayAdapter;

import com.google.firebase.firestore.DocumentReference;
import com.google.firebase.firestore.FieldValue;
import com.google.firebase.firestore.FirebaseFirestore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

public class chatQuestionController {

    private ArrayList<chatQuestion> questions;
    private ArrayAdapter<chatQuestion> listAdapter;

    public chatQuestionController(Context context) {
        questions = new ArrayList<chatQuestion>();
        listAdapter = new chatQuestionAdaptor(context, questions);
    }
    /**
     * THIS CONSTRUCTOR WITH EMPTY PARAMETERS IS FOR TESTING PURPOSES ONLY, DON'T USE IT IN PRODUCTION (CANT MOCK CONTEXT CURRENTLY) IN ExperimentControllerTests
     */
    public chatQuestionController() {
        questions = new ArrayList<chatQuestion>();
    }

    public ArrayAdapter<chatQuestion> getAdapter() {
        return listAdapter;
    }

    public int getSize() {
        return questions.size();
    }

    public ArrayList<chatQuestion> getQuestions() {
        return questions;
    }

    /**
     * This method adds an experiment to the database.
     *
     * @param newQuestion experiment to bed added
     * @param db          the database the experiment will be saved to
     */
    public void addQuestionToDB(chatQuestion newQuestion, FirebaseFirestore db) {
        String EID = newQuestion.getEID();
        DocumentReference newRef = db.collection("Experiments").document(EID).collection("Questions").document();

        Map<String, Object> enterData = new HashMap<>();
        enterData.put("description", newQuestion.getDescription());
        enterData.put("uid", newQuestion.getUID());
        enterData.put("date", newQuestion.getDate());
        enterData.put("eid", EID);
        enterData.put("answerTotal", 0);
        newRef.set(enterData);

        db.collection("Experiments").document(newQuestion.getEID()).update("questionCount", FieldValue.increment(1));

        String questionID = newRef.getId();

        newQuestion.setQID(questionID);  // every experiment should always have a uid which is the uid generated by firestore

        DocumentReference addID = db.collection("Experiments").document(EID).collection("Questions").document(questionID);

        //Maybe change name to EID to keep consistance?
        addID.update("qid", questionID);
    }

    /**
     * sets the experiments variable
     */
    public void setQuestion(ArrayList<chatQuestion> set_questions) {
        questions = set_questions;
    }


    /**
     * This method returns an experiment based on its position in the ListView.
     *
     * @param pos position of experiment in ListView
     * @return experiment that was clicked on
     */
    public chatQuestion getClickedQuestion(int pos) {
        return questions.get(pos);
    }


}

